### ISSUE TITLE
DSText 推理时报错。

### ISSUE THREAD

**Issue by LHE-IT** [weijiawu/TransDETR#28]
您好，在使用DSText 推理时报错：
Traceback (most recent call last):
  File "eval.py", line 905, in <module>
    detr, _, _ = build_model(args)
  File "/home/1080ti/lhe/transdetr_new/TransDETR-main/models/__init__.py", line 24, in build_model
    return build_func(args)
  File "/home/1080ti/lhe/transdetr_new/TransDETR-main/models/TransDETR_ignored.py", line 1066, in build
    criterion = ClipMatcher(num_classes, matcher=img_matcher, weight_dict=weight_dict, losses=losses,language=language)
  File "/home/1080ti/lhe/transdetr_new/TransDETR-main/models/TransDETR_ignored.py", line 64, in __init__
    self.voc, self.char2id, self.id2char = get_vocabulary(language, use_ctc=True)
  File "/home/1080ti/lhe/transdetr_new/TransDETR-main/datasets/data_tools.py", line 306, in get_vocabulary
    with open('/share/lizhuang05/code/pan_pp.pytorch_dev/data/keys.json', encoding='utf-8') as j:
FileNotFoundError: [Errno 2] No such file or directory: '/share/lizhuang05/code/pan_pp.pytorch_dev/data/keys.json'

请问该如何解决？去掉 --is_bilingual 似乎可以正常评估，但是不知道会不会对输出结果造成影响

**Comment by weijiawu** [comment]
不会有影响，DSText只支持英文，不需要--is_bilingual

**Comment by LHE-IT** [comment]
谢谢您的帮助，十分感谢！
